### ISSUE TITLE
Testing of failure conditions is difficult

### ISSUE THREAD

**Issue by daverumph** [Keck-DataReductionPipelines/KeckDRPFramework#34]
I'm trying to write tests for the KPF pipeline, both that operate correctly and ones that I expect to fail in various ways, for example syntax errors in our recipe format.   I have run into two issues:

For tests that I expect to fail,  I expect the pipeline code to raise the RecipeError exception, and the test to confirm that RecipeError was raised by catching it.  In the present Framework implementation, this doesn't work, because 1) MainLoop catches all Exceptions, and 2) it calls os._exit(), and thus my test python code never gets control back at all to validate that the proper exception was raised.  (The error log contains that information, but parsing the error log is not very well suited to automated testing.)

For tests of proper operation, because main_loop exits, those tests must be implemented as shell scripts.  It's workable I suppose, but not my preference for test automation.

I think in general that the Framework needs to shut down by thread joining, and ultimately returning back to the code that started it.  I'm willing to work to that end, but I'm raising this issue to start a conversation about this topic and what if anything to do about it.

--Dave

**Comment by lucarizzi** [comment]
Thank you Dave.

This is a very good point and one of the first infrastructure improvement request that we had in a while.

 

I will discuss with Shui how to proceed.

Luca

**Comment by shkw0k** [comment]
I have been working on improving the framework for the last two weeks.
Amongst other things, I am looking into what happens after the action is completed, successfully or otherwise. 
At this time, I am thinking of introducing a kind of return code for actions.
Maybe we can talk about this over email.

**Comment by lucarizzi** [comment]
Sure that is good. We are reaching a level where my input is less relevant than the input of software engineers so feel free to discuss among the two of you but I am happy to be kept in the loop

**Comment by shkw0k** [comment]
When the framework reaches that point where _exit() is called, it means that there are no more events to process. There could be a problem if there are threads running, that the framework didn't start. 
Pipeline primitives should not start threads in the background. 
If they do start threads, all threads must terminate before leaving the primitive.

Instead of calling os._exit(), I am adding a hook self.on_exit(), so you can override it, just in case, there are other clean up tasks to do.

**Comment by daverumph** [comment]
The KPF pipeline doesn’t start any threads.  I was noting the behavior of the Framework’s main_loop thread.

In trying to test the KPF pipeline, I’m calling framework.start(), and expecting control to get back to my code when the framework processing is finished.  My code never gets control back because of the tread fork and its the call to os._exit().

Do you have any suggestions about how to automate testing?  Generally, we want to run a sequence of tests.  I see that your testing is in shell scripts, and we could do that, but a test framework like pytest expects control to return to the caller, which can then run the next test.

Dave

**Comment by shkw0k** [comment]
I pushed an update to the develop branch.
Take a look at unit_tests/test_run_example.py. 
First, you instantiate the framework object, then ingest some data files.
Then call main_loop(), instead of start().
Then check the output.

You can keep using the same framework object, or get a new one if you want to change pipeline.
